# Kube-burner configuration for Secrets only - sequential execution
# Creates 50,000 Secrets across 10 namespaces (5k each)

global:
  measurements:
    - name: podLatency

jobs:
  # Job 1: Create 50k Secrets across 10 namespaces (5k each)
  - name: secrets-job
    jobType: create
    qps: 20
    burst: 50
    jobIterations: 10
    namespacedIterations: true
    namespace: velero-perf-test
    namespaceLabels:
      velero-test: "performance"
      object-type: "secret"
    cleanup: false
    objects:
      - objectTemplate: templates/secret-template.yaml
        replicas: 5000