# Kube-burner configuration for 150k objects
# Creates 150,000 objects across multiple namespaces for performance testing

global:
  measurements:
    - name: podLatency

jobs:
  # Job 1: Create 50k ConfigMaps across 10 namespaces (5k each)  
  - name: configmaps-150k
    jobType: create
    qps: 25
    burst: 60
    jobIterations: 10
    namespacedIterations: true
    namespace: velero-perf-test
    namespaceLabels:
      velero-test: "performance"
      object-type: "configmap"
    cleanup: false
    objects:
      - objectTemplate: templates/configmap-template.yaml
        replicas: 5000

  # Job 2: Create 50k Secrets across 10 namespaces (5k each)
  - name: secrets-150k
    jobType: create
    qps: 25
    burst: 60
    jobIterations: 10
    namespacedIterations: true
    namespace: velero-perf-test
    namespaceLabels:
      velero-test: "performance"
      object-type: "secret"
    cleanup: false
    objects:
      - objectTemplate: templates/secret-template.yaml
        replicas: 5000

  # Job 3: Create 50k Services across 10 namespaces (5k each)
  - name: services-150k
    jobType: create
    qps: 25
    burst: 60
    jobIterations: 10
    namespacedIterations: true
    namespace: velero-perf-test
    namespaceLabels:
      velero-test: "performance"
      object-type: "service"
    cleanup: false
    objects:
      - objectTemplate: templates/service-template.yaml
        replicas: 5000