apiVersion: v1
kind: Service
metadata:
  name: service-{{.Iteration}}-{{.Replica}}
  namespace: velero-perf-test-{{.Iteration}}
  labels:
    kube-burner-job: create-300k-objects
    kube-burner-index: "{{.Iteration}}"
    kube-burner-uuid: "{{.Iteration}}-{{.Replica}}"
    velero-test: "performance"
    object-type: "service"
    test-batch: "{{.Iteration}}"
spec:
  selector:
    app: test-app-{{.Iteration}}-{{.Replica}}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
  - protocol: TCP
    port: 443
    targetPort: 8443
    name: https
  type: ClusterIP